name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - "taskdn-rust/**"
      - ".github/workflows/rust.yml"
  pull_request:
    branches: [main]
    paths:
      - "taskdn-rust/**"
      - ".github/workflows/rust.yml"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: taskdn-rust

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - run: cargo check --all-features

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - run: cargo clippy --all-features -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - name: Copy demo vault for tests
        run: cp -r ../demo-vault ../dummy-demo-vault
      - run: cargo test --all-features

  test-features:
    name: Test Features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "watch"]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - name: Copy demo vault for tests
        run: cp -r ../demo-vault ../dummy-demo-vault
      - run: cargo test --features "${{ matrix.features }}"

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: -D warnings

  msrv:
    name: MSRV (1.70)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.70
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: taskdn-rust
      - run: cargo check --all-features
