// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read CLI config from ~/.taskdn.json
 */
async readCliConfig() : Promise<Result<CliConfig, CliConfigError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_cli_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the app's data directory path
 */
async getAppDataDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the app's data directory in the system file manager
 */
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if running in development mode
 */
async isDevMode() : Promise<boolean> {
    return await TAURI_INVOKE("is_dev_mode");
},
/**
 * Get dummy vault paths for development testing (only in debug builds)
 */
async getDummyVaultPaths() : Promise<DummyVaultPaths> {
    return await TAURI_INVOKE("get_dummy_vault_paths");
},
/**
 * Initialize the vault with the given configuration.
 * Should be called after preferences are loaded.
 */
async initVault(tasksDir: string, projectsDir: string, areasDir: string, ignore: string[] | null) : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init_vault", { tasksDir, projectsDir, areasDir, ignore }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the vault is configured
 */
async isVaultConfigured() : Promise<boolean> {
    return await TAURI_INVOKE("is_vault_configured");
},
/**
 * Refresh the vault by re-scanning all directories.
 * Call this when receiving the vault-changed event.
 */
async refreshVault() : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_vault") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all tasks from the vault
 */
async listTasks() : Promise<Result<Task[], VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tasks") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all projects from the vault
 */
async listProjects() : Promise<Result<Project[], VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all areas from the vault
 */
async listAreas() : Promise<Result<Area[], VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_areas") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a task by ID
 */
async getTask(id: string) : Promise<Result<Task, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a project by ID
 */
async getProject(id: string) : Promise<Result<Project, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get an area by ID
 */
async getArea(id: string) : Promise<Result<Area, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_area", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new task
 */
async createTask(options: CreateTaskOptions) : Promise<Result<Task, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_task", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new project
 */
async createProject(options: CreateProjectOptions) : Promise<Result<Project, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_project", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing task
 */
async updateTask(update: TaskUpdate) : Promise<Result<Task, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_task", { update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing project
 */
async updateProject(update: ProjectUpdate) : Promise<Result<Project, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project", { update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a task by ID
 */
async deleteTask(id: string) : Promise<Result<null, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_task", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get raw file content for an entity (task, project, or area) by ID.
 * Returns the entire markdown file as a string.
 */
async getEntityRawContent(entityType: string, id: string) : Promise<Result<string, VaultError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_entity_raw_content", { entityType, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "en", "es", "de")
 * If None, uses system locale detection
 */
language: string | null; 
/**
 * Directory containing task files
 */
tasks_dir: string | null; 
/**
 * Directory containing area files
 */
areas_dir: string | null; 
/**
 * Directory containing project files
 */
projects_dir: string | null; 
/**
 * Filenames to ignore when scanning directories
 */
ignore: string[] | null; 
/**
 * Whether to show Obsidian-related features (Open in Obsidian menu item, etc.)
 * Indicates user's vault directories are inside an Obsidian vault
 */
show_obsidian_features: boolean | null }
/**
 * Public area struct exposed to TypeScript via tauri-specta.
 */
export type Area = { 
/**
 * Unique identifier derived from file path
 */
id: string; 
/**
 * Absolute file path to the area
 */
path: string; 
/**
 * Area title from frontmatter
 */
title: string; 
/**
 * Area status (optional per S1 spec)
 */
status: AreaStatus | null; 
/**
 * Area type (e.g., "client", "life-area") - free-form string
 */
areaType: string | null; 
/**
 * Short description
 */
description: string | null; 
/**
 * Markdown body content (after frontmatter)
 */
body: string }
/**
 * Area status enum matching S1 spec Section 5.5
 * Unlike tasks/projects, area status is for visibility only (active vs hidden).
 */
export type AreaStatus = "active" | "archived"
/**
 * Config read from CLI's ~/.taskdn.json
 * Note: CLI uses camelCase field names (tasksDir, areasDir, projectsDir)
 */
export type CliConfig = { tasksDir: string | null; areasDir: string | null; projectsDir: string | null; ignore: string[] | null }
/**
 * Error types for CLI config operations (typed for frontend matching)
 */
export type CliConfigError = 
/**
 * Home directory could not be determined
 */
{ type: "HomeNotFound" } | 
/**
 * ~/.taskdn.json does not exist (CLI not configured - not a real error)
 */
{ type: "FileNotFound" } | 
/**
 * Failed to read the file
 */
{ type: "ReadError"; message: string } | 
/**
 * Failed to parse JSON
 */
{ type: "ParseError"; message: string }
/**
 * Options for creating a new project
 */
export type CreateProjectOptions = { title: string; status: ProjectStatus | null; areaId: string | null; description: string | null; startDate: string | null; endDate: string | null }
/**
 * Options for creating a new task
 */
export type CreateTaskOptions = { title: string | null; status: TaskStatus | null; projectId: string | null; areaId: string | null; scheduled: string | null; due: string | null; deferUntil: string | null }
/**
 * Paths to dummy vault for development testing
 */
export type DummyVaultPaths = { tasks_dir: string; areas_dir: string; projects_dir: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Public project struct exposed to TypeScript via tauri-specta.
 */
export type Project = { 
/**
 * Unique identifier derived from file path
 */
id: string; 
/**
 * Absolute file path to the project
 */
path: string; 
/**
 * Project title from frontmatter
 */
title: string; 
/**
 * Project status (optional per S1 spec)
 */
status: ProjectStatus | null; 
/**
 * Area reference (WikiLink format)
 */
area: string | null; 
/**
 * Start date (ISO 8601)
 */
startDate: string | null; 
/**
 * End date (ISO 8601)
 */
endDate: string | null; 
/**
 * Short description
 */
description: string | null; 
/**
 * Projects that block this one (WikiLink format)
 */
blockedBy: string[] | null; 
/**
 * Markdown body content (after frontmatter)
 */
body: string }
/**
 * Project status enum matching S1 spec Section 4.5
 */
export type ProjectStatus = "planning" | "ready" | "blocked" | "in-progress" | "paused" | "done"
/**
 * Fields that can be updated on a project
 */
export type ProjectUpdate = { id: string; title: string | null; status: ProjectStatus | null; area: string | null; description: string | null; startDate: string | null; endDate: string | null; body: string | null }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
/**
 * Public task struct exposed to TypeScript via tauri-specta.
 * Uses camelCase for TypeScript compatibility.
 */
export type Task = { 
/**
 * Unique identifier derived from file path
 */
id: string; 
/**
 * Absolute file path to the task
 */
path: string; 
/**
 * Task title from frontmatter
 */
title: string; 
/**
 * Task status
 */
status: TaskStatus; 
/**
 * Creation date (ISO 8601)
 */
createdAt: string | null; 
/**
 * Last update date (ISO 8601)
 */
updatedAt: string | null; 
/**
 * Completion date (ISO 8601) - set when status becomes done/dropped
 */
completedAt: string | null; 
/**
 * Due date/datetime (ISO 8601)
 */
due: string | null; 
/**
 * Scheduled date (ISO 8601)
 */
scheduled: string | null; 
/**
 * Defer until date (ISO 8601)
 */
deferUntil: string | null; 
/**
 * Area reference (WikiLink format, e.g., "[[Work]]")
 */
area: string | null; 
/**
 * Project reference (WikiLink format) - first element of projects array
 */
project: string | null; 
/**
 * Markdown body content (after frontmatter)
 */
body: string }
/**
 * Task status enum matching S1 spec Section 3.5
 */
export type TaskStatus = "inbox" | "icebox" | "ready" | "in-progress" | "blocked" | "dropped" | "done"
/**
 * Fields that can be updated on a task
 */
export type TaskUpdate = { 
/**
 * Task ID (required to identify which task to update)
 */
id: string; 
/**
 * New title (if provided)
 */
title: string | null; 
/**
 * New status (if provided)
 */
status: TaskStatus | null; 
/**
 * New project reference (if provided, empty string to clear)
 */
project: string | null; 
/**
 * New area reference (if provided, empty string to clear)
 */
area: string | null; 
/**
 * New scheduled date (if provided, empty string to clear)
 */
scheduled: string | null; 
/**
 * New due date (if provided, empty string to clear)
 */
due: string | null; 
/**
 * New defer-until date (if provided, empty string to clear)
 */
deferUntil: string | null; 
/**
 * New body content (if provided)
 */
body: string | null }
/**
 * Vault operation error types
 */
export type VaultError = 
/**
 * Vault not configured (no directories set in preferences)
 */
{ type: "notConfigured"; message: string } | 
/**
 * File does not exist
 */
{ type: "fileNotFound"; path: string } | 
/**
 * Entity not found by ID
 */
{ type: "entityNotFound"; entity_type: string; id: string } | 
/**
 * Failed to read file
 */
{ type: "readError"; path: string; message: string } | 
/**
 * Failed to write file
 */
{ type: "writeError"; path: string; message: string } | 
/**
 * Failed to parse frontmatter
 */
{ type: "parseError"; path: string; message: string } | 
/**
 * Validation failed
 */
{ type: "validationError"; field: string; message: string } | 
/**
 * File watcher error
 */
{ type: "watcherError"; message: string } | 
/**
 * Internal error
 */
{ type: "internal"; message: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
